name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "dferty"
    - name: Print greeting2
      run: echo "df"
